apiVersion: devops.kubesphere.io/v1alpha1
kind: S2iBuilder
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: s2ibuilder-sample2
spec:
  # Add fields here
   config:
    displayName: "For Test"
    sourceUrl: "https://github.com/sclorg/django-ex"
    imageName: kubespheredev/s2i-test-python
    tag: latest
    builderPullPolicy: if-not-present
   fromTemplate: 
    name: s2ibuildertemplate-python