apiVersion: devops.kubesphere.io/v1alpha1
kind: S2iRun
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: abcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabcabc
spec:
  # Add fields here
  builderName: s2ibuilder-sample2
